### PR TITLE
Examples of evaluating CF metrics

### PR DESCRIPTION
**Pull request by tiffanyj41**
Examples of evaluating Collaborative Filtering Metrics. Data for PRFS comes from https://github.com/apache/spark/blob/master/data/mllib/sample_multiclass_classification_data.txt.

### CODE REVIEW

**Comment by bethke** [comment]
So in src/algorithms/performance_metrics.py, the RMSE calculation the number actual in line 33 is the number of user-item pairs for which a prediction and known rating exist.  Perhaps we should do:

sum_ratings_diff_sq = ( y_predicted.map(lambda x: ((x[0], x[1]), x[2])) ).join( y_actual.map(lambda x: ((x[0], x[1]), x[2])) ) \
       .map( lambda (_, (predictedRating, actualRating)): (predictedRating - actualRating) ** 2 )

return sqrt(sum_ratings_diff_sq.reduce(sum)) / float(sum_ratings_diff_sq.count()) 

Then line 66 (Mean absolute error) it doesn't look like the absolute is being taken...and same deal with the count.  

+    sum_ratings_diff = ( y_predicted.map(lambda x: ((x[0], x[1]), x[2])) ).join( y_actual.map(lambda x: ((x[0], x[1]), x[2])) ) \
+        .map( lambda (_, (predictedRating, actualRating)): abs(predictedRating - actualRating) ) 

+    return sqrt(sum_ratings_diff.reduce(sum)) / float(sum_ratings_diff_sq.count()) 

This way we also do not have to pass in the number of known actuals in the constructor.

**Comment by bethke** [comment]
I really like the example file!  One thing is that we usually don't write the full file extensions as they will always be different for an end user (unless we also post data on the GitHub).  So things like "movielens_10m_ratings.json.gz" are just fine.  That or the file paths could be passed in through the constructors.

**Comment by bethke** [comment]
For the test_simple_prfs() function, I'm not 100% sure if the predictions and true ratings will always be in the same order...which is what I believe the prfs function then assumes.  One way to do it is:

    prediction_rating_pairs = predictions.map(lambda x: ((x[0], x[1]), x[2]))\
        .join(data.map(lambda x: ((x[0], x[1]), x[2])))\
        .map(lambda ((user, item), (prediction, rating)): (user, item, prediction, rating))

    true_vals = np.array(prediction_rating_pairs.map(lambda (user, item, prediction, rating): (user, item, rating)).collect())
    pred_vals = np.array(prediction_rating_pairs.map(lambda (user, item, prediction, rating): (user, item, prediction)).collect())

Then to separate them out...this may actually be a way to do it also with the RDD version.  It may be worth it to see if the answers are the same.  I have seen that the ALS predict all function doesn't always return a result for every known rating.

**Comment by tiffanyj41** [comment]
In src/algorithms/performance_metrics.py, 

sum_ratings_diff_sq is a float. It is already the reduced form of the sum. Therefore, it cannot perform the following reduce function: sum_ratings_diff_sq.reduce(sum). 

Please let me know if I have misunderstood something.

**Comment by tiffanyj41** [comment]
In src/algorithms/performance_metrics.py,

sum_ratings_diff_sq has .reduce(add) included. Is .reduce(add) any difference than .reduce(sum)?

**Comment by tiffanyj41** [comment]
In src/algorithms/performance_metrics.py,

sum_ratings_diff_sq has .reduce(add) included. Is .reduce(add) any difference than .reduce(sum)?

**Comment by tiffanyj41** [comment]
Good catch on the absolute value for MAE. I have revised it accordingly.

**Comment by tiffanyj41** [comment]
The reason why I passed in num_actual as a parameter is because after you performed the sum_ratings_diff_sq operation, it is no longer a RDD; it is a float value. If I wanted to not pass in the number of known actuals, I have to separate the sum_ratings_diff_sq operation into multiple parts. 

In your opinion, is it better to separate the operations into multiple parts so that we do not have to pass in the number of known actuals? Or is it better to just pass in the number of known actuals? I do not have a preference for either way.

**Comment by tiffanyj41** [comment]
I was having that debate myself. I figured since I am in the process of writing the modular framework, I will implement passing the input file there and not in the example as I do not want to waste time on cf_example.py and rewriting it later on for the modular framework. 

I will remove the full extension before merging.

**Comment by tiffanyj41** [comment]
For PRFS, I did not use the movielens data as input so the format is different than user, item, rating. Also test_simple_prfs() is using sklearn's functions which means it has to be in the format of an array and not an RDD. I clarified it in the comment because it can be confusing when reading the code. 

I agree with you. Predictions and true ratings will not always be in the same order. test_prfs() addresses this by creating testPredLabel as follows:     

 testPredAndLabel = testRDD.map(lambda lp: (float(model.predict(lp.features)), lp.label))

When I am incorporating PRFS in the modular framework, I will make sure to use your suggestion and test it using the MovieLens data which I haven't done yet on cf_example.py.

**Comment by bethke** [comment]
In src/algorithms/performance_metrics.py,

What I'm suggesting is to remove the .reduce(sum) from sum_ratings_diff_sq until the return line.  That way you can return the sqrt(sum_ratings_diff_sq.reduce(sum))/sum_ratings_diff_sq.count().

The main issue is that dividing by the number of known ratings isn't correct - it should be the number of rating-prediction pairs.  There is not always a prediction for a known rating.

**Comment by bethke** [comment]
In src/algorithms/performance_metrics.py,

I definitely meant .reduce(add) instead of .reduce(sum).

**Comment by tiffanyj41** [comment]
Gotcha. I didn't quite catch it the first time. Now, I understand what you meant. I have revised it accordingly.

**Pull request merged**
